### ISSUE TITLE
CRT gives error `is not invertible`

### ISSUE THREAD

**Issue by dstahlke** [scheinerman/Mods.jl#11]
julia> CRT(Mod{90}(45), Mod{135}(0))

ERROR: 135 (mod 90) is not invertible

**Comment by scheinerman** [comment]
The Chinese Remainder Theorem applies when the moduli are relatively prime.  Changing the second modulus to one that is relatively prime to 90 gives a correct result:
```
julia> CRT(Mod{90}(45), Mod{137}(0))
6165
```
See [https://mathworld.wolfram.com/ChineseRemainderTheorem.html](https://mathworld.wolfram.com/ChineseRemainderTheorem.html)
