### ISSUE TITLE
"Better" presentation of numbers.

### ISSUE THREAD

**Issue by davidamaro** [scheinerman/Mods.jl#12]
I think that the current `Base.show` implementation could be improved by using Unicode "subscripts". For instance:

```julia
Base.show(io::IO, z::Mod{3}) = print(io, "$(value(z))₃")
Base.show(io::IO, z::Mod{9}) = print(io, "$(value(z))₉")
```

**Comment by scheinerman** [comment]
@davidamaro Interesting idea. Let me think about it. Can you tell me how to code this for general mods, i.e., `Base.show(io::IO, z::Mod{d}) where d = ....` ?

**Comment by davidamaro** [comment]
Hi,

the following code seems to work on my side (not the most elegant implemention, I fear):

```julia
begin
_dict = Dict{Char, Char}()
_dict['0'] = '₀'
_dict['1'] = '₁'
_dict['2'] = '₂'
_dict['3'] = '₃'
_dict['4'] = '₄'
_dict['5'] = '₅'
_dict['6'] = '₆'
_dict['7'] = '₇'
_dict['8'] = '₈'
_dict['9'] = '₉'
end
function _subindex(st::String)
    output = ""
    for c in st
        output *= _dict[c]
    end
    output
end
function _subindex(st::Int64)
    _subindex(st |> string)
end
Base.show(io::IO, z::Mod{N}) where {N} = print(io, "$(value(z))$(_subindex(N))")
```

You can test it: `Mod{17}(2) = 2₁₇`.

**Comment by scheinerman** [comment]
Thanks @davidamaro . I've decide not to implement this. The advantage of the current output is that it can be copy/pasted in the REPL. By the way, you can simplify the build of your dictionary by noting that adding to `'0'` gives the other characters as expected. For example, `'0' + 3` yields `'3'`.  Likewise `'₀' + 4` yields `'₄'`.
