### ISSUE TITLE
Sparse matrix adjoint changes dtype of Mod entries

### ISSUE THREAD

**Issue by lampretl** [scheinerman/Mods.jl#25]
Using Mods v2.1.0 in Julia 1.9.2, when transposing a sparse array, we see that the dtype changes from `Mod{11, Int8}` to `Mod{11, Int64}`:
```
using Mods, SparseArrays

x=sparse(rand(Mod{11,Int8}.(0:3),2,3))
2×3 SparseMatrixCSC{Mod{11, Int8}, Int64} with 5 stored entries:
     ⋅       Mod{11}(1)  Mod{11}(2)
 Mod{11}(3)  Mod{11}(3)  Mod{11}(2)

copy(x')
3×2 SparseMatrixCSC{Mod{11, Int64}, Int64} with 5 stored entries:
     ⋅       Mod{11}(3)
 Mod{11}(1)  Mod{11}(3)
 Mod{11}(2)  Mod{11}(2)
```
Note that transposing a dense matrix preserves the dtype.

**Comment by scheinerman** [comment]
Hi @lampretl, In my re-implementation of `Mods`, I want the value (and mod) type to always be `Int`. If you create `Mod` numbers as `Mod{11}(x)` then everything should be OK. There are problems created by having both `Mod{11,Int}` and `Mod{11,Int8}` numbers interact with each other. 

I would like that the constructor `Int{N,T}(x)` not be available to users, but I don't know how to enforce that. 

I hope this makes sense.

**Comment by scheinerman** [comment]
PS @lampretl, I hope to revise `Mods` to the syntax `Mod{11,Int8}(v)` will not work. The only constructor will look like `Mod{11}(v)`.

**Comment by lampretl** [comment]
@scheinerman Oh no :(. That means that whenever I use huge matrices with `Mod` entries, even over a very small modulus like 2, the allocated memory would be 8x larger that necessary. On `Mods 1.3.3`:
```
julia> x=rand(Mod{2,Int8},10^4,10^4); Float64(sizeof(x))
1.0e8
julia> x=rand(Mod{2,Int},10^4,10^4); Float64(sizeof(x))
8.0e8
```
Is there no way to preserve the old, more optimized functionality?

**Comment by scheinerman** [comment]
> @scheinerman Oh no :(. That means that whenever I use huge matrices with `Mod` entries, even over a very small modulus like 2, the allocated memory would be 8x larger that necessary. On `Mods 1.3.3`:
> 
> ```
> julia> x=rand(Mod{2,Int8},10^4,10^4); Float64(sizeof(x))
> 1.0e8
> julia> x=rand(Mod{2,Int},10^4,10^4); Float64(sizeof(x))
> 8.0e8
> ```
> 
> Is there no way to preserve the old, more optimized functionality?

The new functionality in Version 2.x.x is no more efficient than that of Version 1.x.x, so the best I can offer is to use the previous version. There are some logic problems in Version 1, but they shouldn’t be an issue if you’re using byte-size integers. But do check the arithmetic for moduli near 255 to see if arithmetic works ok.

**Comment by lampretl** [comment]
If I understand correctly, v1.3.4 is the last version that allows for `T=Mod{m,Int8}`? 

Is it guaranteed to give correct `x+y`, `x*y`, `x^n` for `x ::T`, `y ::T`, `n ::Int`? If not, do you have any examples? 

Also, does your arithmetic guarantee that overflows don't occur, or do I need to use `T=Mod{m,SafeInt8}`? Also, is it the same if I use `T=Mod{m,UInt8}`?

**Comment by scheinerman** [comment]
> If I understand correctly, v1.3.4 is the last version that allows for `T=Mod{m,Int8}`?

Yes. That's right. Version 2 *might* allow that at the moment, but I'm poised to remove that option. 


> 
> Is it guaranteed to give correct `x+y`, `x*y`, `x^n` for `x ::T`, `y ::T`, `n ::Int`? If not, do you have any examples?

The problems I had were with using `Int128` so I think you should be fine.


> 
> Also, does your arithmetic guarantee that overflows don't occur, or do I need to use `T=Mod{m,SafeInt8}`? Also, is it the same if I use `T=Mod{m,UInt8}`?

I think `Int8` should be fine but I really don't know about the other two types. I haven't tested any of this.

**Comment by scheinerman** [comment]
@lampretl I have created a `MiniMods` module that works just like `Mods`, but the moduli must be between 2 and 127 so everything fits in a single byte. I hope this might be useful to you. A very new version is [now available](https://github.com/scheinerman/MiniMods.jl.git) (but unregistered) on GitHub: 

`https://github.com/scheinerman/MiniMods.jl.git`

I need to do a bit more work (e.g., testing) but please let me know if this is helpful. The only change you might need in your code is to globally replace `Mod` with `MiniMod`. (I hope.)

**Comment by lampretl** [comment]
@scheinerman That's awesome, thank you!!! : ) 
I see you used `Int8` as the underlying dtype. Wouldn't it be better to have `UInt8` to be able to go to 255 with values?

One more question: if having Int8 Mods _is_ still possible, wouldn't it be better to have all this functionality inside your original package Mods.jl (to not fragment everything into several packages)? If necessary, we could have dtypes hardcoded into the Struct. That way, we'd have types `Mod8{m}, Mod16{m}, Mod32{m}, Mod64{m}, Mod128{m}` that would internally use `UInt8, UInt16, UInt32, UInt64, UInt128`. This would be analogous to `SaferIntegers.jl` package, where they have `SafeUInt8,...,SafeUInt128`.

**Comment by lampretl** [comment]
If the separate, hardcoded Mod types were implemented, perhaps the performance would be better. At the moment, this is quite an issue. With Mods.jl v2.2.1, we have:
```
julia> using SaferIntegers, Mods
julia> begin n=10^3;  m=11;
       x = Int.(      rand(-9:9,(n,n)));  @time x*x; 
       y = SafeInt64.(rand(-9:9,(n,n)));  @time (y*y) .%m;
       z = Mod{m}.(   rand(-9:9,(n,n)));  @time z*z; end;
  0.434071 seconds (5 allocations: 7.659 MiB)
  1.476792 seconds (9 allocations: 15.289 MiB)
538.278712 seconds (6.17 G allocations: 114.895 GiB, 35.82% gc time)
```
Due to this, when working with huge matrices, it makes more sense to use `SafeInt64` and `.%m` instead of `Mod{m}`. 
I don't know much about the compiler, so this is just a naive suggestion on how to improve the package : ).

**Comment by scheinerman** [comment]
> @scheinerman That's awesome, thank you!!! : ) I see you used `Int8` as the underlying dtype. Wouldn't it be better to have `UInt8` to be able to go to 255 with values?

@lampretl I'm delighted this is helpful to you. 

I'll consider that suggestion. I'm mildly concerned about how unsigned integers work (and display). I think the use case for a `MiniMod` is likely to be only with small, prime mods, but that would be an easy change. 

What I'm considering is defining a `SmallInt` type inside `MiniMods` and every instance of `Int8` be replaced by `SmallInt`. That way a user could fork the package, change a single line, and have (say) `UInt8` or `Int16` instead.

> 
> One more question: if having Int8 Mods _is_ still possible, wouldn't it be better to have all this functionality inside your original package Mods.jl (to not fragment everything into several packages)? If necessary, we could have dtypes hardcoded into the Struct. That way, we'd have types `Mod8{m}, Mod16{m}, Mod32{m}, Mod64{m}, Mod128{m}` that would internally use `UInt8, UInt16, UInt32, UInt64, UInt128`. This would be analogous to `SaferIntegers.jl` package, where they have `SafeUInt8,...,SafeUInt128`.

I think I want to keep `MiniMods` as a separate package and not fold that code into `Mods`. If someone wants both, they can do `using Mods, MiniMods`. But the advantage I see (perhaps this is minor) is if one only uses `MiniMods`, then the `Mod` symbol is not exported so it would be easy to detect a typo in which someone used `Mod{17}(6)` when they meant `MiniMod{17}(6)`.

```
julia> using MiniMods

julia> a = Mod{17}(6)
ERROR: UndefVarError: `Mod` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1

julia> a = MiniMod{17}(6)
MiniMod{17}(6)
```

**Comment by scheinerman** [comment]
@lampretl You wrote:

> If the separate, hardcoded Mod types were implemented, perhaps the performance would be better. At the moment, this is quite an issue. With Mods.jl v2.2.1, we have:
> 
> ```
> julia> using SaferIntegers, Mods
> julia> begin n=10^3;  m=11;
>        x = Int.(      rand(-9:9,(n,n)));  @time x*x; 
>        y = SafeInt64.(rand(-9:9,(n,n)));  @time (y*y) .%m;
>        z = Mod{m}.(   rand(-9:9,(n,n)));  @time z*z; end;
>   0.434071 seconds (5 allocations: 7.659 MiB)
>   1.476792 seconds (9 allocations: 15.289 MiB)
> 538.278712 seconds (6.17 G allocations: 114.895 GiB, 35.82% gc time)
> ```
> 
> Due to this, when working with huge matrices, it makes more sense to use `SafeInt64` and `.%m` instead of `Mod{m}`. I don't know much about the compiler, so this is just a naive suggestion on how to improve the package : ).

Eek. I'm not at all sure how to think about this! What I can say is that `MiniMods` does a lot better than `Mods`:

```
julia> n=10^3;  m=11;

julia> z = Mod{m}.(   rand(-9:9,(n,n)));  

julia> zz = MiniMod{m}.(   rand(-9:9,(n,n)));  

julia> @time z*z;
175.764039 seconds (6.17 G allocations: 115.022 GiB, 28.82% gc time, 0.25% compilation time)

julia> @time zz*zz;
  6.845978 seconds (1.56 M allocations: 104.051 MiB, 0.45% gc time, 6.65% compilation time)
```

**Comment by scheinerman** [comment]
> > @scheinerman That's awesome, thank you!!! : ) I see you used `Int8` as the underlying dtype. Wouldn't it be better to have `UInt8` to be able to go to 255 with values?
> 
> @lampretl I'm delighted this is helpful to you.
> 
> I'll consider that suggestion. I'm mildly concerned about how unsigned integers work (and display). I think the use case for a `MiniMod` is likely to be only with small, prime mods, but that would be an easy change.
> 
> What I'm considering is defining a `SmallInt` type inside `MiniMods` and every instance of `Int8` be replaced by `SmallInt`. That way a user could fork the package, change a single line, and have (say) `UInt8` or `Int16` instead.
> 

**UPDATE**: I made the change by adding a line:
```
const SmallInt = Int8
```
and then replacing `Int8` with `SmallInt`. 

But: If `SmallInt` is defined to be `UInt8` it seems to work ok (I have not done much testing) but printing is a tad ugly:
```
julia> a = MiniMod{200}(23)
MiniMod{200}(0x17)
```

**Comment by scheinerman** [comment]
Hello again @lampretl 
> **UPDATE**: I made the change by adding a line:
> 
> ```
> const SmallInt = Int8
> ```
> 
> and then replacing `Int8` with `SmallInt`.
> 
> But: If `SmallInt` is defined to be `UInt8` it seems to work ok (I have not done much testing) but printing is a tad ugly:
> 
> ```
> julia> a = MiniMod{200}(23)
> MiniMod{200}(0x17)
> ```

Worse than that! Subtraction doesn't work. I'm going to forbid unsigned values for `SmallInt`. If someone needs a modulus greater than 127, they can either use `Mods` or edit the code to set `SmallInt = Int16` (or larger).

Version 0.1.0 is in its three-day waiting period for registration. Once that's complete, I'll update to 0.1.1 with this change.

**Comment by lampretl** [comment]
> But: If SmallInt is defined to be UInt8 it seems to work ok (I have not done much testing) but printing is a tad ugly:

It is ugly, but you can (and usually should) override how it is displayed (regardless of whether you use Int's or UInt's):

```
julia> n=5; Mod{11}.(rand(-100:100,(n,n)))
5×5 Matrix{Mod{11}}:
  Mod{11}(4)  Mod{11}(4)   Mod{11}(8)  Mod{11}(10)   Mod{11}(1)
  Mod{11}(7)  Mod{11}(8)  Mod{11}(10)   Mod{11}(3)   Mod{11}(4)
  Mod{11}(0)  Mod{11}(8)   Mod{11}(0)   Mod{11}(0)  Mod{11}(10)
 Mod{11}(10)  Mod{11}(8)   Mod{11}(2)   Mod{11}(2)  Mod{11}(10)
  Mod{11}(2)  Mod{11}(5)   Mod{11}(1)   Mod{11}(6)   Mod{11}(4)
  
julia> function Base.show(io ::IO, x ::Mod) ::Nothing  
               print(io, Int128(x.val)) end;
               
julia> n=5; Mod{11}.(rand(-100:100,(n,n)))
5×5 Matrix{Mod{11}}:
 3   1   3  1   9
 7   7   4  4  10
 5   8   3  1   5
 3   0  10  6   5
 4  10   5  8   2
```

> Worse than that! Subtraction doesn't work. I'm going to forbid unsigned values for SmallInt. If someone needs a modulus greater than 127, they can either use Mods or edit the code to set SmallInt = Int16 (or larger).

If you defined your line 4 in arithmetic.jl
[(-)(a::Mod{N}) where {N} = Mod{N}(-value(a))](https://github.com/scheinerman/Mods.jl/blob/8e5f9444a7ec947246c783f91d82bd7c1d9bd930/src/arithmetic.jl#L4)
a bit differently, namely replacing `-value(a)` with `N-value(a)`, shouldn't that enable subtraction when using UInt's?

> What I'm considering is defining a SmallInt type inside MiniMods and every instance of Int8 be replaced by SmallInt. That way a user could fork the package, change a single line, and have (say) UInt8 or Int16 instead.
> 
> I think I want to keep MiniMods as a separate package and not fold that code into Mods. If someone wants both, they can do using Mods, MiniMods. But the advantage I see (perhaps this is minor) is if one only uses MiniMods, then the Mod symbol is not exported so it would be easy to detect a typo in which someone used Mod{17}(6) when they meant MiniMod{17}(6).

I get what you're aiming at, but my humble suggestion is to retain everything inside Mods.jl. Most mathematicians/engineers have a problem and wish a quick and efficient solution. They are not even sure whether to use Mathematica, Python sympy, SageMath, MatLab, ..., so ideally, they install Julia, install Mods.jl, have all its functionality immediately available, try it out, and realize this is what they've been looking for. 

If they have to clone a repository, go into the source code, edit it, debug the changed script, it is too much and 90% of them will abandon the approach for a simpler solution elsewhere. That's why I think all functionality should become available with a single `] add Mods`. I noticed you also have Chinese remainder theorem functions. That would also be nice to have available immediately. Mods.jl is a small package, I think it would handle fine all the exported functionality. But it's just my opinion. : )

If you used separate `Mod8, ..., Mod128`, you wouldn't have to write 5-times as much code as you currently have, you'd just use

```
for T ∈ [Mod8, ..., Mod128]
    # define all functions here, something like:
    +(x ::$T, y ::$T) = $T(x.val+y.val)
end
```

In any case, the most critical thing currently is to improve the performance without sacrificing correctness.
> Eek. I'm not at all sure how to think about this! What I can say is that MiniMods does a lot better than Mods:
julia> n=10^3;  m=11;
julia> z = Mod{m}.(   rand(-9:9,(n,n)));  
julia> zz = MiniMod{m}.(   rand(-9:9,(n,n)));  
julia> @time z * z;
175.764039 seconds (6.17 G allocations: 115.022 GiB, 28.82% gc time, 0.25% compilation time)
julia> @time zz * zz;
  6.845978 seconds (1.56 M allocations: 104.051 MiB, 0.45% gc time, 6.65% compilation time)

Minor nitpick: When you do benchmarks like above, it is best to run the code twice, so that no time is spend on compilation.

As you can see, there is over a million allocations and 100MiB used, to compute the matrix product, even though using just Int or SafeInt uses less than 10 allocations and 1MiB. Two possible causes of this that come to mind: 

https://github.com/scheinerman/Mods.jl/blob/8e5f9444a7ec947246c783f91d82bd7c1d9bd930/src/arithmetic.jl#L1
When you multiply two 10^3 x 10^3 matrices, you have to compute 10^9 multiplications+additions. But every time you compute x+y or x*y, you allocate a bigger chunk of memory via `widen()`. That must be painful for the compiler. I'm not sure how to do all computations in-place, without occasional silent overflows. : ( But probably this could be improved.

https://github.com/scheinerman/Mods.jl/blob/8e5f9444a7ec947246c783f91d82bd7c1d9bd930/src/constructors.jl#L6
If I understand correctly, every time we compute x+y or x*y, a new `Mod` is created and those assertions are checked. That seems like a lot of unnecessary work. Is this correct? If I do 
```
julia> n=10^6;  T=Mod{11};  x, y = [rand(T.(0:10),n) for _=1:2];  @time x .+ y;
  0.444562 seconds (6.00 M allocations: 122.070 MiB, 33.32% gc time)
```
will Julia check once or a million times whether `N isa Integer && N > 1` and `N <= typemax(Int)`?

**Comment by lampretl** [comment]
Let's say we use type `T ∈ [UInt8, ..., UInt128]` for `val` and `M=Mod{N,T}`. If `N<typemax(T)//2`, then additions
`+(x ::M, y ::M) = M(x.val + y.val)`
are guaranteed to not overflow. How could we implement `*`efficiently and not overflow? 

For instance, if `T=Int8`, so that `typemax(T)=255`, and `N=101`, how would we multiply `x*y` where `x=y=50`, without resorting to `UInt16`or higher?

**Comment by scheinerman** [comment]
@lampretl I'll consider folding `MiniMods` into `Mods`, but the rest is too much work for me right now. As for the speed, I ran tests using `BenchmarkTools`. Using `@btime` runs the same code several times and reports the best speed (I think). It is better than `@time` as you mentioned.
```
julia> using MiniMods, Mods, LinearAlgebra, BenchmarkTools

julia> m = 17;

julia> n = 100;

julia> A = rand(Mod{m}, n, n);

julia> B = MiniMod.(A);

julia> @btime det(A)
  45.492 ms (1970121 allocations: 37.65 MiB)
Mod{17}(1)

julia> @btime det(B)
  1.869 ms (3 allocations: 10.83 KiB)
MiniMod{17}(1)

julia> @btime inv(A);
  343.919 ms (7970125 allocations: 152.25 MiB)

julia> @btime inv(B);
  16.060 ms (5 allocations: 31.56 KiB)
```

**Comment by lampretl** [comment]
Understood. 

Btw, I suspect your timings are faster because of n=10^2. With n=10^3 or n=10^4, multiplying `Int` matrices will be incomparably faster than `MiniMod`matrices (regardless of using `@time` or `@btime`).

**Comment by lampretl** [comment]
Dear Ed, by reading your code and using ChatGPT, I've learned the basics on how to use parametric structs. I've written my own implementation of integers modulo m:
```
struct Mod8{m}
    val ::UInt8 
    function Mod8{m}(val ::tw) where {m,tw <:UInt8}
        return new{m}(mod(val,m)) end end;  # Note: mod(val,m) is always positive, but rem(val,m) = val % m preserves the sign.
struct Mod16{m}
    val ::UInt16
    function Mod16{m}(val ::tw) where {m,tw <:UInt16}
        return new{m}(mod(val,m)) end end;
struct Mod32{m}
    val ::UInt32
    function Mod32{m}(val ::tw) where {m,tw <:UInt32}
        return new{m}(mod(val,m)) end end;
struct Mod64{m}
    val ::UInt64
    function Mod64{m}(val ::tw) where {m,tw <:UInt64}
        return new{m}(mod(val,m)) end end;
struct Mod128{m}
    val ::UInt128
    function Mod128{m}(val ::tw) where {m,tw <:UInt128}
        return new{m}(mod(val,m)) end end;
function modIntType(m ::Integer) ::DataType
    #= Create a type that has enough space so that overflow does not happen. 
    The condition m ≤ sqrt(typemax(UIntN)) makes sure that multiplication val*val is never larger than the underlying UIntN. =#
    @assert 2 ≤ m  
    if     m ≤ sqrt(typemax(UInt8))     return Mod8{  UInt8(  m)}
    elseif m ≤ sqrt(typemax(UInt16))    return Mod16{ UInt16( m)}
    elseif m ≤ sqrt(typemax(UInt32))    return Mod32{ UInt32( m)}
    elseif m ≤ sqrt(typemax(UInt64))    return Mod64{ UInt64( m)}
    elseif m ≤ sqrt(typemax(UInt128))   return Mod128{UInt128(m)}
    else error("modulus m must be in [2,...,2^128-1]") end end;
for T ∈ (Mod8,Mod16,Mod32,Mod64,Mod128)
    for tw ∈ (Int8,Int16,Int32,Int64,Int128,BigInt,SafeInt8,SafeInt16,SafeInt32,SafeInt64,SafeInt128)
        T{m}(val ::tw) where m = T{m}(typeof(m)(mod(val,m))) end;
    Base.zero(::T{m}) where m = T{m}(typeof(m)(0));
    Base.one( ::T{m}) where m = T{m}(typeof(m)(1));
    Base.:+(x ::T{m}) where m = x;
    Base.:-(x ::T{m}) where m = T{m}(m - x.val);
    Base.:+(x ::T{m}, y ::T{m}) where m = T{m}(x.val + y.val);
    Base.:-(x ::T{m}, y ::T{m}) where m = T{m}(x.val + m - y.val);
    Base.:*(x ::T{m}, y ::T{m}) where m = T{m}(x.val * y.val);
    Base.inv(x ::T{m}) where m = T{m}(invmod(x.val, m)); 
    Base.:^(x ::T{m}, k ::Integer) where m = T{m}(powermod(x.val, k, m)); 
    Base.:*(x ::T{m}, y ::Integer) where m = *(x, T{m}(y));
    Base.:*(x ::Integer, y ::T{m}) where m = *(T{m}(x), y);
    function Base.show(io ::IO, x ::T) ::Nothing  
        print(io, BigInt(x.val)) end; end;
```
Forgive my concise dense style of writing. It's just what I prefer and is easier for me to understand. How to use it:
```
julia> T=modIntType(11)
Mod8{0x0b}

julia> n=10^1; x=rand(T.(-20:20),(n,n))
10×10 Matrix{Mod8{0x0b}}:
 10  8  3  5  2  8   9  10  7  7
 2   1  7  0  2  4   8  8   7  3
 6   2  2  6  8  1   4  3   3  8
 6   9  0  7  7  2   1  10  2  5
 10  2  9  7  7  3   9  10  8  6
 6   0  8  3  0  10  4  4   3  9
 6   1  7  4  2  5   0  0   4  0
 0   9  9  1  4  10  4  7   2  5
 5   6  8  0  2  9   2  8   5  1
 5   4  2  1  1  1   6  6   7  10

julia> n=10^3; x=rand(T.(-20:20),(n,n));   @time x*x;
  3.679816 seconds (5 allocations: 1008.172 KiB)
```

As you can see, it needs less than 4sec, compared to your Mod{11}'s 539sec, which is a 146x speedup. I am sure that when multiplying 10^4 x 10^4 matrices, the speedup would be even larger. I suggest that, when you have time, you refactor your code, to use this approach. IMO, having efficient operations is key when developing a package.

**Comment by scheinerman** [comment]
Hi @lampretl (Leon): Lots for me to consider here and I have a "day job" too ... Can we perhaps more this conversation to email? I'm at ers@jhu.edu 

I am very interested in speed up, but not at the expense of correctness. I'm concerned about overflow, especially in multiplication. 

For example, in your proposal:
```
Base.:*(x ::T{m}, y ::T{m}) where m = T{m}(x.val * y.val);
```
If the type is (say) `Int8` and the result of `x.val * y.val` exceeds 127, what happens? Here's my worry:
```
julia> using MiniMods

julia> a = MiniMod{100}(90)
MiniMod{100}(90)

julia> a+a
MiniMod{100}(80)

julia> MiniMod{100}(a.val + a.val)
MiniMod{100}(24)   ### THIS IS WRONG 

julia> MiniMod{100}(a.val * a.val)
MiniMod{100}(8)    ### THIS IS ALSO WRONG
```

I wonder if the speedup you're seeing is because you avoid widening? 

In any case, how do you feel about moving the conversation to email? (I'm ok either way.)

**Comment by lampretl** [comment]
Of course, without correctness, it would all be for nothing. But no overflow should be occurring. Notice that in all my Mod types, I used unsigned integers, to have enough space for calculations. In particular, for `T=Mod8{m}` the underlying type UInt8 has values `[0,...,255]`, so the modulus `m` must be at most `floor(sqrt(255))=15`. Multiplying `x ::T`and `y ::T` first computes `x.val * y.val`, which is safely within `[0,...,255]`, then calls `T` on it, which computes `mod(x.val * y.val, m)` and sends it to [0,...,15], hence no overflow.

If you wanted to compute modulo `m=90`, you'd be using `T = modIntType(90) = Mod16{0x005a}`. 

Yes, of course we can move to email, or Slack/Telegram/Signal, whatever suits you. I'll send you a message.
