### ISSUE TITLE
use of abstract element types not recommended

### ISSUE THREAD

**Issue by KlausC** [scheinerman/Mods.jl#3]
See [julia docu](https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-fields-with-abstract-type-1)
instead of 
```
struct Mod
    val::Integer
    mod::Integer
end
```
you should use
```
struct Mod{T<:Integer}
    val::T
    mod::T
end
```

or even
```
struct Mod{T<:Unsigned} <:Real
    ...
end
```
The constructors should derive the concrete types from their arguments.

**Comment by scheinerman** [comment]
OK. I think I understand the issue and will try an update.

**Comment by scheinerman** [comment]
Update posted.
