### ISSUE TITLE
Base.:(==) is not symmetric for Mod and Integer

### ISSUE THREAD

**Issue by pddshk** [scheinerman/Mods.jl#35]
# Problem description
```julia
julia> using Mods

julia> Mod{5}(2) == 2
true

julia> 2 == Mod{5}(2)
ERROR: MethodError: no method matching modulus(::Int64)
...
```

This also lead to impossibility of following usages

```julia
julia> any(==(Mod{5}(2)), 1:5)
ERROR: MethodError: no method matching modulus(::Int64)
```

# Possible solution
Define
```julia
Base.:(==)(i::Integer, m::AbstractMod) = i == value(m)
```

**Comment by scheinerman** [comment]
Thanks for finding this error. I'll fix and post a new version soon.

**Comment by scheinerman** [comment]
New version submitted. It'll take a bit of time to percolate through ... maybe another 30 mins? Thanks again!
