### ISSUE TITLE
New tag and release

### ISSUE THREAD

**Issue by Liozou** [scheinerman/Mods.jl#4]
Would it be possible to tag and release the current version of Mods.jl? The last tag registered in the General repository is 0.1.0 (see https://github.com/JuliaRegistries/General/blob/master/M/Mods/Versions.toml), which is two years old and lacks the latest improvements (concrete types on parameters, overflow protection).

**Comment by scheinerman** [comment]
I just tried to do this but, frankly, I don't really understand how this works. I believe I have tagged a new version as 0.2.0. It may take a bit of time to do all the checks. Please let me know if it worked.

**Comment by Liozou** [comment]
I must admit I don't know how this works myself, sorry... But the general procedure is explained here: https://github.com/JuliaRegistries/General/blob/master/README.md
From what I understand, you just locally updated your `Project.toml`, so your package now has version 0.2.0. However, since you did not forward this update to the [General](https://github.com/JuliaRegistries/General.git) registry, new users who do `] add Mods` or `Pkg.add("Mods")` will receive the latest version of the package present in the General registry, which is still v0.1.0.
There is also the [Registrator.jl](https://github.com/JuliaRegistries/Registrator.jl) package that seems to automate the task of updating the version of your package on the General registry, but I don't know how it works either.

Anyway, in the meantime I can simply do `] add Mods#master` to pull the latest version of `Mods.jl`, which is what I need at the moment.

**Comment by scheinerman** [comment]
I think it's working! I'm going to close this issue, but let me know if you think it's still broken.
