### ISSUE TITLE
Base.abs function

### ISSUE THREAD

**Issue by pddshk** [scheinerman/Mods.jl#9]
Julia is able to solve linear systems with modulus with just `A \ b` where `A` is `Matrix` and `b` is `Vector` with eltype `Mod{p}`. However this needs `Base.abs` to be defined on `Mod`s. Here's the code

```Base.abs(x::Mod) = abs(value(x))```

**Comment by pddshk** [comment]
Just opened a PR, you can link it to this issue

**Comment by scheinerman** [comment]
Clever! Thanks for suggesting this.
